# Generated by Django 5.2.3 on 2025-07-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bs_grouping", "0002_adminaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("member_create", "Member Created"),
                    ("member_edit", "Member Edited"),
                    ("member_delete", "Member Deleted"),
                    ("group_create", "Group Created"),
                    ("group_edit", "Group Edited"),
                    ("group_delete", "Group Deleted"),
                    ("member_assign", "Member Assigned to Group"),
                    ("member_remove", "Member Removed from Group"),
                    ("member_move", "Member Moved Between Groups"),
                    ("leader_assign", "Leader Assigned"),
                    ("leader_remove", "Leader Removed"),
                    ("grouping_run", "Automatic Grouping Run"),
                    ("grouping_stop", "Automatic Grouping Stopped"),
                    ("group_rebalance", "Groups Rebalanced"),
                    ("impersonate", "Admin Impersonated Member"),
                ],
                max_length=20,
            ),
        ),
    ]
