# Generated by Django 5.2.3 on 2025-07-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="year_of_study",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
