# Generated by Django 5.2.1 on 2025-07-09 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BibleStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("book", models.CharField(max_length=100)),
                ("total_sessions", models.PositiveIntegerField()),
                ("current_session", models.PositiveIntegerField()),
                ("meeting_day", models.CharField(max_length=20)),
                ("meeting_time", models.CharField(max_length=50)),
                ("meeting_venue", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Bible Studies",
            },
        ),
        migrations.CreateModel(
            name="WeeklyReflection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.PositiveIntegerField()),
                ("scripture_reference", models.CharField(max_length=100)),
                ("scripture_text", models.TextField()),
                ("reflection_text", models.TextField()),
                ("discussion_question", models.TextField(blank=True)),
                ("date", models.DateField()),
                (
                    "bible_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registration.biblestudy",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
