# Generated by Django 5.2.3 on 2025-07-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_alter_user_year_of_study"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sessions_attended",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
