# Generated by Django 5.2.3 on 2025-07-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_alter_user_sessions_attended"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="leader_before",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="leader_now",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
