# Generated by Django 5.2.3 on 2025-07-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_alter_user_leader_before_alter_user_leader_now"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, default="unknown", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.IntegerField(default=0, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(default="", max_length=254, unique=True),
        ),
    ]
