# Generated by Django 5.2.3 on 2025-07-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_user_full_name_user_user_id_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.IntegerField(default=0),
        ),
    ]
